#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name=$(basename $buildpack_url)
    buildpack_commit="$2"

    echo "Fetching $buildpack_name..."

    set +e
    git clone --branch $buildpack_commit --depth 1 $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name &>/dev/null
    SHALLOW_CLONED=$?
    set -e
    if [ $SHALLOW_CLONED -ne 0 ]; then
        # if the shallow clone failed partway through, clean up and try a full clone
        rm -rf $BUILDPACK_INSTALL_PATH/$buildpack_name
        git clone --quiet $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
        pushd $BUILDPACK_INSTALL_PATH/$buildpack_name &>/dev/null
            git checkout --quiet $buildpack_commit
        popd &>/dev/null
    else
        # clean .git directory
        rm -rf $BUILDPACK_INSTALL_PATH/$buildpack_name/.git 
    fi

    echo "Done."
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-multi.git         master
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-ruby.git          enterprise-3.3
download_buildpack https://github.com/goodrain/heroku-buildpack-nodejs-backports.git   v76.20180103
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-java.git          v38.2017102702
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-gradle.git        enterprise-3.3
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-grails.git        enterprise-3.3
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-play.git          enterprise-3.3
download_buildpack https://github.com/goodrain/heroku-buildpack-python-backports.git   v137.2018081501
download_buildpack https://github.com/goodrain/heroku-buildpack-php-backports.git      v82.2018052901
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-clojure.git       enterprise-3.3
download_buildpack git@code.goodrain.com:buildpacks/heroku-buildpack-scala.git         enterprise-3.3
download_buildpack https://github.com/goodrain/heroku-buildpack-go-backports.git       master
download_buildpack https://github.com/goodrain/heroku-buildpack-static-backports       master
download_buildpack git@code.goodrain.com:buildpacks/goodrain-buildpack-java-war.git    enterprise-3.3
download_buildpack git@code.goodrain.com:buildpacks/goodrain-buildpack-java-jar.git    enterprise-3.3

# 修改权限

chown rain.rain /tmp/buildpacks -R
