#!/usr/bin/env bash

if [[ $ES_ENABLE_APM == "true" ]];then
    ES_TRACE_AGENT_ID=${SERVICE_ID:0:10}
    PINPOINT_AGETN_VERSION=2.0.3
    PINPOINT_AGENT_PATH=/app/.pinpoint
    COLLECTOR_IP_HOST=${COLLECTOR_IP_HOST:-127.0.0.1}
    PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT=${PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT:-9991}
    PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT=${PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT:-9991}
    PROFILER_TRANSPORT_STAT_COLLECTOR_PORT=${PROFILER_TRANSPORT_STAT_COLLECTOR_PORT:-9992}
    PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT=${PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT:9993}
    PROFILER_SAMPLING_RATE=${PROFILER_SAMPLING_RATE:-1}
    PROFILER_TRANSPORT_MODULE=${PROFILER_TRANSPORT_MODULE:-GRPC}
    COLLECTOR_TCP_PORT=${COLLECTOR_TCP_PORT:-9994}
    COLLECTOR_STAT_PORT=${COLLECTOR_STAT_PORT:-9995}
    COLLECTOR_SPAN_PORT=${COLLECTOR_SPAN_PORT:-9996}
    SPRING_PROFILES=${SPRING_PROFILES:-release}
    sed -i "/profiler.transport.grpc.collector.ip=/ s/=.*/=${COLLECTOR_IP_HOST}/" "${PINPOINT_AGENT_PATH}/pinpoint-agent-${PINPOINT_AGETN_VERSION}/profiles/release/pinpoint-env.config"
    sed -i "/profiler.collector.ip=/ s/=.*/=${COLLECTOR_IP_HOST}/" "${PINPOINT_AGENT_PATH}/pinpoint-agent-${PINPOINT_AGETN_VERSION}/profiles/release/pinpoint-env.config"
    export JAVA_OPTS="$JAVA_OPTS -javaagent:${PINPOINT_AGENT_PATH}/pinpoint-agent-${PINPOINT_AGETN_VERSION}/pinpoint-bootstrap-${PINPOINT_AGETN_VERSION}.jar -Dpinpoint.agentId=${HOSTNAME##*-} -Dpinpoint.applicationName=${ES_TRACE_APP_NAME:-${SERVICE_NAME:-$HOSTNAME}} -Dpinpoint.profiler.profiles.active=release"
fi